DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS author;


CREATE TABLE author
(
	id SERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(32),
	last_name VARCHAR(32) NOT NULL 

);

CREATE TABLE book
(
	id SERIAL NOT NULL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	lexile SMALLINT NOT NULL,
	genre VARCHAR(32) NOT NULL,
	author_id INT NOT NULL REFERENCES public.author(id)
);

CREATE TABLE series
(
	id SERIAL NOT NULL PRIMARY KEY,
	series_name VARCHAR(100),
	author_id INT NOT NULL REFERENCES public.author(id)

);



